env: "Hopper-v3"
next_steps: 50
random_steps: 5000
max_train_steps: 3000000
evaluate_freq: 5000
save_freq: 20

policy_dist: "Gaussian"
batch_size: 2048
mini_batch_size: 64
hidden_width: 64

lr_a: 0.0003
lr_c: 0.0003

gamma: 0.99
lamda: 0.95
epsilon: 0.2
K_epochs: 10
entropy_coef: 0.01

weight_reg: 0.0
seed: 0
GAMMA: "1"
# rho: 0.000000000000001
rho: 0.01

use_adv_norm: true
use_state_norm: true
use_lr_decay: true
use_grad_clip: true
use_orthogonal_init: true
set_adam_eps: true
use_tanh: true
adaptive_alpha: false
use_sam: false

use_reward_scaling: true
use_reward_norm: false
reward_noise: false

convergence_threshold: 8000
reward_noise_std: 0.1

# to debug
device: "cpu"
hard: "False"